/**
 * Liste de cartes de reference, extraite de `seedTestCollection.ts`.
 *
 * Elle vivait en dur dans ce script, qui ne garnissait qu'un utilisateur.
 * `seedAllUsers.ts` en avait besoin aussi : plutot que de la recopier — et de
 * la voir diverger a la premiere modification — les deux scripts la lisent
 * desormais ici.
 */

export type Seed = { name: string; qty: number };

/** Deck principal : 59 cartes distinctes, 119 exemplaires. */
export const MAIN_SEEDS: Seed[] = [
  { name: 'Blue-Eyes White Dragon', qty: 3 },
  { name: 'Dark Magician', qty: 3 },
  { name: 'Red-Eyes Black Dragon', qty: 2 },
  { name: 'Exodia the Forbidden One', qty: 1 },
  { name: 'Left Arm of the Forbidden One', qty: 1 },
  { name: 'Right Arm of the Forbidden One', qty: 1 },
  { name: 'Left Leg of the Forbidden One', qty: 1 },
  { name: 'Right Leg of the Forbidden One', qty: 1 },
  { name: 'Ash Blossom & Joyous Spring', qty: 4 },
  { name: 'Effect Veiler', qty: 4 },
  { name: 'Maxx "C"', qty: 4 },
  { name: 'Ghost Ogre & Snow Rabbit', qty: 3 },
  { name: 'Nibiru, the Primal Being', qty: 2 },
  { name: 'Cyber Dragon', qty: 3 },
  { name: 'Elemental HERO Sparkman', qty: 2 },
  { name: 'Elemental HERO Neos', qty: 1 },
  { name: 'Elemental HERO Avian', qty: 1 },
  { name: 'Elemental HERO Burstinatrix', qty: 1 },
  { name: 'Buster Blader', qty: 1 },
  { name: 'Kuriboh', qty: 1 },
  { name: 'Winged Kuriboh', qty: 1 },
  { name: 'Sangan', qty: 1 },
  { name: 'Witch of the Black Forest', qty: 1 },
  { name: 'D.D. Crow', qty: 2 },
  { name: 'PSY-Framegear Gamma', qty: 2 },
  { name: 'Fossil Dyna Pachycephalo', qty: 1 },
  { name: 'Jinzo', qty: 1 },
  { name: 'Summoned Skull', qty: 2 },
  { name: 'Gemini Elf', qty: 1 },
  { name: 'Man-Eater Bug', qty: 1 },
  { name: 'Pot of Greed', qty: 1 },
  { name: 'Monster Reborn', qty: 1 },
  { name: 'Raigeki', qty: 1 },
  { name: 'Dark Hole', qty: 1 },
  { name: 'Change of Heart', qty: 1 },
  { name: 'Mystical Space Typhoon', qty: 4 },
  { name: 'Book of Moon', qty: 3 },
  { name: 'Called by the Grave', qty: 3 },
  { name: 'Foolish Burial', qty: 2 },
  { name: 'Pot of Extravagance', qty: 3 },
  { name: 'Pot of Desires', qty: 3 },
  { name: 'Twin Twisters', qty: 4 },
  { name: 'Cosmic Cyclone', qty: 3 },
  { name: 'Terraforming', qty: 1 },
  { name: 'Reinforcement of the Army', qty: 1 },
  { name: 'Mirror Force', qty: 2 },
  { name: 'Solemn Judgment', qty: 1 },
  { name: 'Solemn Warning', qty: 3 },
  { name: 'Solemn Strike', qty: 3 },
  { name: 'Bottomless Trap Hole', qty: 3 },
  { name: 'Trap Hole', qty: 2 },
  { name: 'Torrential Tribute', qty: 2 },
  { name: 'Skill Drain', qty: 3 },
  { name: 'Compulsory Evacuation Device', qty: 3 },
  { name: 'Infinite Impermanence', qty: 4 },
  { name: 'Trap Trick', qty: 2 },
  { name: 'Imperial Order', qty: 1 },
  { name: 'Waboku', qty: 3 },
  { name: 'Magic Cylinder', qty: 2 },
];

/** Extra Deck : 22 cartes distinctes, 27 exemplaires. */
export const EXTRA_SEEDS: Seed[] = [
  { name: 'Blue-Eyes Ultimate Dragon', qty: 1 },
  { name: 'Dark Paladin', qty: 1 },
  { name: 'Elemental HERO Flame Wingman', qty: 1 },
  { name: 'Elemental HERO Neos Knight', qty: 1 },
  { name: 'Elemental HERO The Shining', qty: 1 },
  { name: 'Cyber End Dragon', qty: 1 },
  { name: 'Stardust Dragon', qty: 2 },
  { name: 'Black Rose Dragon', qty: 1 },
  { name: 'Ancient Fairy Dragon', qty: 1 },
  { name: 'Junk Warrior', qty: 1 },
  { name: 'Formula Synchron', qty: 2 },
  { name: 'Number 39: Utopia', qty: 2 },
  { name: 'Number 17: Leviathan Dragon', qty: 1 },
  { name: 'Steelswarm Roach', qty: 1 },
  { name: 'Number 41: Bagooska the Terribly Tired Tapir', qty: 1 },
  { name: 'Tornado Dragon', qty: 1 },
  { name: 'Firewall Dragon', qty: 1 },
  { name: 'Decode Talker', qty: 1 },
  { name: 'Knightmare Phoenix', qty: 2 },
  { name: 'Knightmare Cerberus', qty: 2 },
  { name: 'Knightmare Unicorn', qty: 1 },
  { name: 'Accesscode Talker', qty: 1 },
];
